server:
  port: ${APP_PORT:8080}

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:buyers}
    username: ${DB_USERNAME:buyers}
    password: ${DB_PASSWORD:buyers}
  liquibase:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:buyers}
    user: ${DB_USERNAME:buyers}
    password: ${DB_PASSWORD:buyers}
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

app:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:telegramToken}
    username: ${TELEGRAM_BOT_USERNAME:telegramUsername}
  security:
    authentication:
      jwt:
        base64-secret: ${SECURITY_AUTHENTICATION_JWT_BASE64_SECRET:base64-secret}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000