server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:irk-buyers-club}
    username: ${DB_USERNAME:irk-buyers-club}
    password: ${DB_PASSWORD:irk-buyers-club}
  liquibase:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:irk-buyers-club}
    user: ${DB_USERNAME:irk-buyers-club}
    password: ${DB_PASSWORD:irk-buyers-club}
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true